# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"syscall.h\"\n";

sub entry {
    my $name = shift;
    my $uname = uc($name);
    print ".global $name\n";
    print "$name:\n";
    print " li a7, SYS_$uname\n";
    print " ecall\n";
    print " ret\n";
}

entry("halt");
entry("exit");
entry("exec");
entry("wait");
entry("remove");
entry("open");
entry("read");
entry("write");
entry("seek");
entry("tell");
entry("close");
entry("fstat");
entry("mmap");
entry("munmap");
entry("chdir");
entry("mkdir");
